package except;
import java.util.Scanner;
class UserExcep extends RuntimeException
{
	Scanner scan=new Scanner(System.in);
	public UserExcep(){}
	public UserExcep(String k)
	{
		System.out.println("user defined exception raised "+k);
	}
	void display() //throws Exception
	{		
		try
		{
		System.out.println("Enter your Age:");
		int age=scan.nextInt();
		if(!(age>=18))
		{
			throw new UserExcep("your error name ");
			//throw new Exception("not accept age");
		}
		else
		{
			System.out.println("Age is accepted");
		}
		}
		catch(Exception e)
		{
			System.out.println(" error "+e.toString());
			display();
		}
		
	}	
}

public class ThrowError {

	public static void main(String[] args)  {
		// TODO Auto-generated method stub

		UserExcep ob=new UserExcep();
		
		try
		{
		ob.display();
		}
		catch(Exception e)
		{
			System.out.println("error1");
		}
		}
	}
	//==================================================
	import java.util.Scanner;

public class UserExcep extends Exception{
Scanner scan=new Scanner(System.in);
 
    String ans="";
   public UserExcep(){}
   public UserExcep(String e)
   {
	   System.out.println("Exception raised "+e);
   }
   void display()
   {
	   try
	   {
	   System.out.println("Enter age:");
	   int age=scan.nextInt();
	   if(age<=17 || age>=101)
	   {
		   
		   throw new UserExcep("please enter 18 to 100");
	   }	
	   else
		   System.out.println("age accepted");
	   }
	   catch(Exception e)
	   {
		   ans=e.toString();
		   System.out.println("errrror :"+ans);		   
	   }
	   finally
	   {
		   if(ans.equals(""))
			   System.out.println("program finished no error");
		   else
		   {
			   System.out.println("program finished with error");
			   ans="";
			   display();
		   }
			   
	   }	   
   }	
	public static void main(String[] args) {
		UserExcep ob=new UserExcep();
		ob.display();
	}
}



